# Generated by Django 3.2.11 on 2022-01-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
